config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/about', to: 'home#about'

  resources :customer_services, expect: %i[create edit] do
    collection do
      post '/initiate', to: 'customer_services#initiate'
      # post '/refine', to: 'customer_services#refine'
    end
  end

  resources :customers

  get '/dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :customer_services, dependent: :destroy
  validates :name, :email, :age, :cpf, :address, :health_care_number, :telephone, presence: true
end

app/models/customer_service.rb
class CustomerService < ApplicationRecord
  belongs_to :customer, optional: true
  validates :code, :service_type, :medical_service_type, presence: true

  enum service_type: { default: 5, preferential: 10 }
  enum medical_service_type: { general: 5, specialist: 10 }

  def generate_code
    self.code = SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customer_services_controller.rb
class CustomerServicesController < ApplicationController
  before_action :fetch_customer_service, only: %i[show]

  def new
    @customer_service = CustomerService.new
  end

  def initiate
    @customer_service_params = customer_service_params
    @customer_service = CustomerService.new
  end

  def create
    @customer_service = CustomerService.new(customer_service_params)
    @customer_service.generate_code
    redirect_to @customer_service if @customer_service.save
  end

  def show; end

  private

  def customer_service_params
    params.require(:customer_service).permit(:code, :service_type, :medical_service_type)
  end

  def fetch_customer_service
    @customer_service = CustomerService.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :fetch_customer, only: %i[show edit update]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def show; end

  def create
    @customer = Customer.new(customer_params)
    return redirect_to dashboard_path(cpf: @customer.cpf), notice: 'Cadastro Realizado com sucesso' if @customer.save

    render :new
  end

  def edit; end

  def update 
    return redirect_to dashboard_path(cpf: @customer.cpf),
    notice: 'Cadastro Atualizado com sucesso' if @customer.update(customer_params)

    render :edit
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :telephone, :address, :health_care_number, :cpf, :age)
  end

  def fetch_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @cpf = params[:cpf]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customer_services/initiate.html.erb
<%= form_with(model: @customer_service) do |form| %>
  <%= form.hidden_field :service_type, value: @customer_service_params[:service_type] %>
  <%= form.hidden_field :medical_service_type, value: 'general' %>
  <div class='btn btn-primary'>
    <%= form.submit 'Clínico Geral' %>
  </div>
<% end %>
<%= form_with(model: @customer_service) do |form| %>
  <%= form.hidden_field :service_type, value: @customer_service_params[:service_type] %>
  <%= form.hidden_field :medical_service_type, value: 'specialist' %>
  <div class='btn btn-primary'>
    <%= form.submit 'Especialista' %>
  </div>
<% end %>

app/views/customer_services/new.html.erb
<%= form_with(model: @customer_service, url: initiate_customer_services_path, data: { turbo: false }) do |form| %>
  <%= form.hidden_field :service_type, value: 'default' %>
  <div class='btn btn-primary'>
    <%= form.submit 'Atendimento Padrão' %>
  </div>
<% end %>
<%= form_with(model: @customer_service, url: initiate_customer_services_path, data: { turbo: false }) do |form| %>
  <%= form.hidden_field :service_type, value: 'preferential' %>
  <div class='btn btn-primary'>
    <%= form.submit 'Atendimento Preferencial' %>
  </div>
<% end %>

app/views/customer_services/show.html.erb
<div>
  <%= "Sua senha é: #{@customer_service.code}" %>
</div>

app/views/customers/edit.html.erb
<%= render 'shared/errors', object: @customer %>
<%= form_with(model: @customer, data: {turbo: false}) do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :name, :Nome, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :age, :Idade, class: "form-label" %>
        <%= form.number_field :age, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :cpf, :Cpf, class: "form-label" %>
        <%= form.text_field :cpf, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :email, :Email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :address, :Endereço, class: "form-label" %>
        <%= form.text_field :address, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :telephone, :Telefone, class: "form-label" %>
        <%= form.text_field :telephone, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :health_care_number, 'Número do plano de saúde', class: "form-label" %>
        <%= form.text_field :health_care_number, class: "form-control" %>
      </div>
      <%= form.submit "Atualizar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/customers/index.html.erb
<div>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Idade</th>
        <th>Cpf</th>
        <th>Telefone</th>
        <th>Endereço</th>
        <th>Número do plano de saúde</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.name %></td>
          <td><%= customer.email %></td>
          <td><%= customer.age %></td>
          <td><%= customer.cpf %></td>
          <td><%= customer.telephone %></td>
          <td><%= customer.address %></td>
          <td><%= customer.health_care_number %></td>
          <td><%= link_to 'Editar', edit_customer_path(customer) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <%= link_to 'Voltar', '/dashboard' %>
</div>

app/views/customers/new.html.erb
<%= render 'shared/errors', object: @customer %>
<%= form_with(model: @customer, data: {turbo: false}) do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :name, :Nome, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :age, :Idade, class: "form-label" %>
        <%= form.number_field :age, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :cpf, :Cpf, class: "form-label" %>
        <%= form.text_field :cpf, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :email, :Email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :address, :Endereço, class: "form-label" %>
        <%= form.text_field :address, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :telephone, :Telefone, class: "form-label" %>
        <%= form.text_field :telephone, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :health_care_number, 'Número do plano de saúde', class: "form-label" %>
        <%= form.text_field :health_care_number, class: "form-control" %>
      </div>
      <%= form.submit "Registrar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1>DashBoard</h1>
<div>
  <%= link_to 'Registro de Visitante', new_customer_path %>
  <%= link_to 'Todos os Visitantes', customers_path %>
</div>
<div>
  <%= form_with(url: '#') do |form| %>
    <p>
      <%= form.label 'Cliente(cpf)' %>
      <%= form.text_field 'cpf', value: @cpf %>
    </p>
    <p>
      <%= form.label 'Cliente(codigo)' %>
      <%= form.text_field 'code', value: @code %>
    </p>
    <p>
      <%= form.submit 'Atrelar Atendimento', disabled: @cpf.blank? %>
    </p>
  <% end %>
</div>

app/views/home/about.html.erb
Sobre Mim

app/views/home/index.html.erb
<%= link_to 'Iniciar Atendimento', new_customer_service_path %>
<%= link_to 'Sobre Mim', about_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyTicket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/notice_alert' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each.with_index do |message, id| %>
    <div style="display: block !important" id="toast_<%= id %>" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto">Error</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close" onclick="closeToast('#toast_<%= id %>')"></button>
      </div>
      <div class="toast-body">
        <%= message %>
      </div>
    </div>
  <% end %>
<% end %>
<script>
  function closeToast(target) {
    const tar = document.querySelector(target);
    tar.style = 'none';
  }
</script>

app/views/shared/_notice_alert.html.erb
<% if notice %>
  <p><%= notice %></p>
<% end %>
<% if alert %>
  <p><%= alert %></p>
<% end %>